-- Trigger: POST-QUERY  (pegar en el bloque CARGA_RECLAMOS_MASIVOS)
--
-- FRM-41050: no asignar con :BLOCK.ITEM := valor si el registro no es
-- actualizable (Update Allowed = No, o filas PROCESADO bloqueadas).
-- Se usa COPY + se deja el registro en QUERY_STATUS.

DECLARE
  V_ESTATUS  NUMBER;
  V_FORMA_P  VARCHAR2(50);
  V_DESC     VARCHAR2(200);
  V_FORMA    VARCHAR2(50);
  V_REC      NUMBER := :SYSTEM.TRIGGER_RECORD;
BEGIN
  IF :CARGA_RECLAMOS_MASIVOS.ESTATUS_REGISTRO = 'PROCESADO' THEN
    SET_ITEM_INSTANCE_PROPERTY('CARGA_RECLAMOS_MASIVOS.ESTATUS_REGISTRO',
                               CURRENT_RECORD,
                               VISUAL_ATTRIBUTE,
                               'ESTATUS_COLOR_EXITO');
  ELSIF :CARGA_RECLAMOS_MASIVOS.ESTATUS_REGISTRO IS NOT NULL THEN
    SET_ITEM_INSTANCE_PROPERTY('CARGA_RECLAMOS_MASIVOS.ESTATUS_REGISTRO',
                               CURRENT_RECORD,
                               VISUAL_ATTRIBUTE,
                               'ESTATUS_COLOR_ERROR');
  END IF;

  IF :CARGA_RECLAMOS_MASIVOS.ANO        IS NULL
  OR :CARGA_RECLAMOS_MASIVOS.COMPANIA   IS NULL
  OR :CARGA_RECLAMOS_MASIVOS.RAMO       IS NULL
  OR :CARGA_RECLAMOS_MASIVOS.SECUENCIAL IS NULL THEN
    RETURN;
  END IF;

  BEGIN
    SELECT R.ESTATUS, R.FOR_PAG
      INTO V_ESTATUS, V_FORMA_P
      FROM RECLAMACION R
     WHERE R.ANO        = :CARGA_RECLAMOS_MASIVOS.ANO
       AND R.COMPANIA   = :CARGA_RECLAMOS_MASIVOS.COMPANIA
       AND R.RAMO       = :CARGA_RECLAMOS_MASIVOS.RAMO
       AND R.SECUENCIAL = :CARGA_RECLAMOS_MASIVOS.SECUENCIAL;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      IF :CARGA_RECLAMOS_MASIVOS.ESTATUS_REGISTRO = 'PROCESADO' THEN
        V_DESC := 'NO EXISTE RECLAMACION!';
      ELSE
        RETURN;
      END IF;
    WHEN TOO_MANY_ROWS THEN
      V_DESC := 'RECLAMACION DUPLICADA!';
  END;

  IF V_DESC IS NULL AND V_ESTATUS IS NOT NULL THEN
    BEGIN
      SELECT E.DESCRIPCION
        INTO V_DESC
        FROM ESTATUS E
       WHERE E.TIPO   = 'RECLAMACION'
         AND E.CODIGO = V_ESTATUS;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        V_DESC := 'ESTATUS ' || TO_CHAR(V_ESTATUS);
      WHEN TOO_MANY_ROWS THEN
        V_DESC := 'ESTATUS ' || TO_CHAR(V_ESTATUS);
    END;
  END IF;

  IF V_FORMA_P = 'C' THEN
    V_FORMA := 'CHEQUE';
  ELSIF V_FORMA_P IS NOT NULL THEN
    V_FORMA := 'TRANSFERENCIA';
  END IF;

  -- Permite llenar items de display aunque la fila no sea actualizable.
  SET_RECORD_PROPERTY(V_REC, 'CARGA_RECLAMOS_MASIVOS', UPDATE_ALLOWED, PROPERTY_TRUE);
  SET_ITEM_INSTANCE_PROPERTY('CARGA_RECLAMOS_MASIVOS.ESTATUS_RECLAMACION_DESC',
                             CURRENT_RECORD, UPDATE_ALLOWED, PROPERTY_TRUE);
  SET_ITEM_INSTANCE_PROPERTY('CARGA_RECLAMOS_MASIVOS.FORMA_PAGO',
                             CURRENT_RECORD, UPDATE_ALLOWED, PROPERTY_TRUE);

  COPY(NVL(V_DESC, ''),  'CARGA_RECLAMOS_MASIVOS.ESTATUS_RECLAMACION_DESC');
  COPY(NVL(V_FORMA, ''), 'CARGA_RECLAMOS_MASIVOS.FORMA_PAGO');

  -- No dejar la fila como CHANGED (Forms intentaria UPDATE).
  SET_RECORD_PROPERTY(V_REC, 'CARGA_RECLAMOS_MASIVOS', STATUS, QUERY_STATUS);

  SET_ITEM_INSTANCE_PROPERTY('CARGA_RECLAMOS_MASIVOS.ESTATUS_RECLAMACION_DESC',
                             CURRENT_RECORD, UPDATE_ALLOWED, PROPERTY_FALSE);
  SET_ITEM_INSTANCE_PROPERTY('CARGA_RECLAMOS_MASIVOS.FORMA_PAGO',
                             CURRENT_RECORD, UPDATE_ALLOWED, PROPERTY_FALSE);

  IF :CARGA_RECLAMOS_MASIVOS.ESTATUS_REGISTRO = 'PROCESADO' THEN
    SET_RECORD_PROPERTY(V_REC, 'CARGA_RECLAMOS_MASIVOS', UPDATE_ALLOWED, PROPERTY_FALSE);
  END IF;
END;
