-- Program Unit: PR_CARGAR_INFO_RECLAMACION
-- Trae estatus y forma de pago DESDE RECLAMACION.
-- Llamar:
--   1) desde POST-QUERY (solo si la reclamacion ya existe en BD)
--   2) desde el trigger/boton que INSERTA o carga la reclamacion,
--      DESPUES de que el registro ya este en RECLAMACION (idealmente post-COMMIT)

PROCEDURE PR_CARGAR_INFO_RECLAMACION IS
  V_ESTATUS   NUMBER;
  V_FORMA_P   VARCHAR2(50);
  V_DESC      VARCHAR2(200);
BEGIN
  :CARGA_RECLAMOS_MASIVOS.ESTATUS_RECLAMACION_DESC := NULL;
  :CARGA_RECLAMOS_MASIVOS.FORMA_PAGO               := NULL;

  -- Sin llave completa no hay reclamacion que buscar.
  IF :CARGA_RECLAMOS_MASIVOS.ANO        IS NULL
  OR :CARGA_RECLAMOS_MASIVOS.COMPANIA   IS NULL
  OR :CARGA_RECLAMOS_MASIVOS.RAMO       IS NULL
  OR :CARGA_RECLAMOS_MASIVOS.SECUENCIAL IS NULL THEN
    RETURN;
  END IF;

  BEGIN
    SELECT R.ESTATUS,
           R.FOR_PAG
      INTO V_ESTATUS,
           V_FORMA_P
      FROM RECLAMACION R
     WHERE R.ANO        = :CARGA_RECLAMOS_MASIVOS.ANO
       AND R.COMPANIA   = :CARGA_RECLAMOS_MASIVOS.COMPANIA
       AND R.RAMO       = :CARGA_RECLAMOS_MASIVOS.RAMO
       AND R.SECUENCIAL = :CARGA_RECLAMOS_MASIVOS.SECUENCIAL;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      -- Reclamacion todavia no existe (carga pendiente o POST-QUERY temprano).
      -- Solo avisar si el registro de carga ya se marco PROCESADO.
      IF :CARGA_RECLAMOS_MASIVOS.ESTATUS_REGISTRO = 'PROCESADO' THEN
        :CARGA_RECLAMOS_MASIVOS.ESTATUS_RECLAMACION_DESC := 'NO EXISTE RECLAMACION!';
      END IF;
      RETURN;
    WHEN TOO_MANY_ROWS THEN
      :CARGA_RECLAMOS_MASIVOS.ESTATUS_RECLAMACION_DESC := 'RECLAMACION DUPLICADA!';
      RETURN;
  END;

  BEGIN
    SELECT E.DESCRIPCION
      INTO V_DESC
      FROM ESTATUS E
     WHERE E.TIPO   = 'RECLAMACION'
       AND E.CODIGO = V_ESTATUS;

    :CARGA_RECLAMOS_MASIVOS.ESTATUS_RECLAMACION_DESC := V_DESC;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      :CARGA_RECLAMOS_MASIVOS.ESTATUS_RECLAMACION_DESC := 'ESTATUS ' || NVL(TO_CHAR(V_ESTATUS), '?');
    WHEN TOO_MANY_ROWS THEN
      :CARGA_RECLAMOS_MASIVOS.ESTATUS_RECLAMACION_DESC := 'ESTATUS ' || TO_CHAR(V_ESTATUS);
  END;

  IF V_FORMA_P IS NOT NULL THEN
    IF V_FORMA_P = 'C' THEN
      :CARGA_RECLAMOS_MASIVOS.FORMA_PAGO := 'CHEQUE';
    ELSE
      :CARGA_RECLAMOS_MASIVOS.FORMA_PAGO := 'TRANSFERENCIA';
    END IF;
  END IF;
END;
