-- Program Unit: PR_PINTAR_ESTATUS_REGISTRO
-- Pinta ESTATUS_REGISTRO de la fila actual. No consulta RECLAMACION.

PROCEDURE PR_PINTAR_ESTATUS_REGISTRO IS
BEGIN
  IF :CARGA_RECLAMOS_MASIVOS.ESTATUS_REGISTRO IS NULL THEN
    RETURN;
  END IF;

  IF :CARGA_RECLAMOS_MASIVOS.ESTATUS_REGISTRO = 'PROCESADO' THEN
    SET_ITEM_INSTANCE_PROPERTY('CARGA_RECLAMOS_MASIVOS.ESTATUS_REGISTRO',
                               CURRENT_RECORD,
                               VISUAL_ATTRIBUTE,
                               'ESTATUS_COLOR_EXITO');
  ELSE
    SET_ITEM_INSTANCE_PROPERTY('CARGA_RECLAMOS_MASIVOS.ESTATUS_REGISTRO',
                               CURRENT_RECORD,
                               VISUAL_ATTRIBUTE,
                               'ESTATUS_COLOR_ERROR');
  END IF;
END;
